# not using tuple !
#base: null

data:
  init_data:
    base: null
    path: ./dataset/camvid
    classes: ["Rood","Sky"]
    channels: [3,3]
    palette: [[128,64,128],[128,128,128]] 
    one_hot_encoding: true
    background_adding: true
    image_size: [256, 256]
    batch_size: 32
    #test_batch_size: 32
    seed: 48
    create_validation_set: false
  augmentation:
    base: ./config/_base/aug.yaml
    aug_type: albumentations # only albumentations
    load_style: file # module
    train: null
    test: null

model:
  base: null
  model_class: Unet 
  backbone: null 
  pre_trained: false
  n_filters:  [16, 32, 64, 128, 256]
  final_activation: sigmoid
       
compile:
  base: null
  optimizer: {name: adam}
  metrics: [accuracy]
  losses: [binary_crossentropy]

trainer:
  base: null
  epochs: 20
  batch_size: 32

callbacks:
  base: null
  check_point:
  lr_scheduler:
  
    

  
# model:
#   class_path: anomalib.models.Padim
#   init_args:
#     input_size:
#       - 256 # Height
#       - 256 # Width
#     backbone: resnet18
#     pre_trained: true
#     layers:
#       - layer1
#       - layer2
#       - layer3

# compile:
#   adaptive_threshold: true
#   default_image_threshold: null
#   default_pixel_threshold: null
#   image_metric_names:
#     - F1Score
#     - AUROC
#   pixel_metric_names:
#     - F1Score
#     - AUROC
#   normalization_method: min_max

# trainer:
#   logger: true
#   accelerator: auto # <"cpu", "gpu", "tpu", "ipu", "hpu", "auto">
#   accumulate_grad_batches: 1
#   amp_backend: native
#   auto_lr_find: false
#   auto_scale_batch_size: false
#   auto_select_gpus: false
#   benchmark: false
#   check_val_every_n_epoch: 1 # Don't validate before extracting features.
#   default_root_dir: null
#   detect_anomaly: false
#   deterministic: false
#   devices: 1
#   enable_checkpointing: true
#   enable_model_summary: true
#   enable_progress_bar: true
#   fast_dev_run: false
#   gpus: null # Set automatically
#   gradient_clip_val: 0
#   ipus: null
#   limit_predict_batches: 1.0
#   limit_test_batches: 1.0
#   limit_train_batches: 1.0
#   limit_val_batches: 1.0
#   log_every_n_steps: 50
#   max_epochs: 1
#   max_steps: -1
#   max_time: null
#   min_epochs: null
#   min_steps: null
#   move_metrics_to_cpu: false
#   multiple_trainloader_mode: max_size_cycle
#   num_nodes: 1
#   num_processes: null
#   num_sanity_val_steps: 0
#   overfit_batches: 0.0
#   plugins: null
#   precision: 32
#   profiler: null
#   reload_dataloaders_every_n_epochs: 0
#   replace_sampler_ddp: true
#   resume_from_checkpoint: null
#   sync_batchnorm: false
#   tpu_cores: null
#   track_grad_norm: -1
#   val_check_interval: 1.0 # Don't validate before extracting features.