#load_style: file # or module # it find automatically
aug_type: albumentations
train: # if load_style is modeule, get function from like this => aug.test:transforms
  resize: { height: 300, width: 300 }
  one_of: { transforms: [horizontal_flip, vertical_flip], p: 0.3 }
  random_rotate_90:
  randon_brightness_contrast: { brigtness_limit: 0.2, constrast_limit: 0.2, p: 0.5 }
  sharpen: { alpha: [0.2, 0.5], lightness: [0.5, 1], p: 0.5 }

val:
  resize: { height: 300, width: 300 }

test:
  resize: { height: 300, width: 300 }
